#---
#spring:
#  application:
#    name: spring-cloud-eureka
#  profiles: peer1
#server:
#  port: 8000
#eureka:
#  instance:
#    hostname: peer1
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/
#---
#spring:
#  application:
#    name: spring-cloud-eureka
#  profiles: peer2
#server:
#  port: 8001
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://peer1:8000/eureka/,http://peer3:8002/eureka/
#---
#spring:
#  application:
#    name: spring-cloud-eureka
#  profiles: peer3
#server:
#  port: 8002
#eureka:
#  instance:
#    hostname: peer3
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/
#
#
##spring.application.name=spring-cloud-eureka
#
##server.port=8000
## 表示是否将自己注册到Eureka Server,默认为true
##eureka.client.register-with-eureka=false
## 表示是否从Eureka Server获取注册信息,默认为true
##eureka.client.fetch-registry=false
#
## 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
## 默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
##eureka.client.serviceUrl.defaultZone=http://localhost:${server.port}/eureka/